config/routes.rb
Rails.application.routes.draw do
  root "contacts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   get '/about' => 'pages#about'
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :last_name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :last_name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :phone, presence: true, length: { minimum: 10, maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :last_name, :phone, :address, :gender, :age)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/_form.html.erb
<div>
<% if @contact.errors.any? %>
  <h6>The following errors prevented the new contact from being saved</h6>
  <ul id="errors">
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
</div>

<div id="form">
  <%= form_with(model: @contact, local: true) do |f| %>
    <div>
      <%= f.label :name, {class: "form_label"} %>
      <%= f.text_field :name, {class: "inputs"} %>
    </div>
     <br>

    <div>
      <%= f.label :last_name, {class: "form_label"} %>
      <%= f.text_field :last_name, {class: "inputs"}  %>
    </div>
     <br>

    <div>
      <%= f.label :phone, {class: "form_label"} %>
      <%= f.text_field :phone, {class: "inputs"}  %>
    </div>
     <br>

    <div>
      <%= f.label :address, {class: "form_label"} %>
      <%= f.text_area :address, {class: "inputs"} %>
    </div>
     <br>

    <div>
      <%= f.label :gender, {class: "form_label"} %>
      <%= f.select :gender, ["", "male", "female", "prefer not answer"], {class: "inputs"}  %>
    </div>
     <br>

    <div>
      <%= f.label :age, {class: "form_label"} %>
      <% ;%>
      <%= f.select :age, 0..100, {class: "select"} %>
    </div>
     <br>

    <div>
      <%= f.submit "Submit", id:"submit"%>
    </div>
  <% end %>
     <br>

</div>

app/views/contacts/edit.html.erb
<div class="new_edit">

  <div id="title_edit">
    <p> Submit the form again, once is modifided!</p>
  </div>

  <div>
    <%= render 'form', contact: @contact %>
  </div>

  <div class="bottom_links">
    <%= link_to 'Show', @contact %> | <%= link_to 'Back', contacts_path %>
  </div>

</div>

app/views/contacts/index.html.erb
 <div id="home_page">
  <div id="create_new_contact">
    <p id="notice"><%= notice %></p>
    <%= link_to 'Create New Contact', new_contact_path, class:"create_new_contact" %>
  </div>

  <div class="table-responsive-lg">
    <table class="table table-striped table-dark table-hover">
    <thead id="table_header">
      <tr>
       <th scope="col">Name: </th>
          <th scope="col">Lastname: </th>
          <th scope="col">Phone: </th>
          <th scope="col" >Address: </th>
          <th scope="col">Gender:</th>
          <th scope="col">Age:</th>
          <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
        <% @contacts.each do |contact| %>
          <tr scope="row">
            <td> <%= contact.name %></td>
            <td> <%= contact.last_name %></td>
            <td id="address_header"> <a href="tel:+1<%= contact.phone %>">+1<%= contact.phone %></a></td>
            <td> <%= contact.address %></td>
            <td> <%= contact.gender %></td>
            <td> <%= contact.age %></td>
            <td id="show_link"><%= link_to 'Show', contact %></td>
            <td id="edit_link"><%= link_to 'Edit', edit_contact_path(contact) %></td>
            <td id="delete_link">
              <%= link_to 'Delete', contact, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

 </div>

app/views/contacts/new.html.erb
<div id="edit">

  <div id="title_edit">
    <h1>New Contact</h1>
  </div>

  <div>
    <%= render 'form', contact: @contact %>
  </div>

  <div class="bottom_links">
    <%= link_to 'Cancel', contacts_path %>
  </div>

</div>

app/views/contacts/show.html.erb
<div id="show_id">
  <p id="notice">
    <%= notice %>
  </p>
  <div class="show_class">
    <p><%= @contact.name%> </p> <br>
    <p> <%= @contact.last_name%></p>
  </div>

  <div class="show_class">
    <a href="tel:+1<%= @contact.phone%>">+1<%= @contact.phone%></a>
  </div>

  <div class="show_class">
    <%= @contact.address%>
  </div>

  <div class="show_class">
    <%= @contact.gender%>
  </div>

  <div class="show_class" >
    <%= @contact.age%>
  </div>

  <div class="bottom_links">
    <%= link_to 'Edit', edit_contact_path(@contact) %> | <%= link_to 'Back', contacts_path %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<h6>Proudy created by <span id="name">Pedro Ramirez</span> </h6>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="nav">
  <a class="navbar-brand" href="#"><span id="title">Rails</span> Contact Application</a>
  <button id="button1" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Home', contacts_path, {id:"link1"}%>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, {id:"link2"}%>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendsDirectory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/nav' %>

    <div id="main_container">
      <%= yield %>
    </div>

    <%= render '/layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div id="about">
  <h1>Rails Contact Aplication</h1>

  <p>This application was created in April of 2021, using ruby on rails and bootstrap</p>

  <article>
    <p>
      Rails Contact Application was the first application that I created to improve my programming skills!
    </p>
  </article>
  <article>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus quisquam autem ab quidem repudiandae cupiditate delectus eligendi voluptatum aliquam pariatur vel, minima molestiae illum facere. Nam voluptatibus maiores beatae. Repellat?
    </p>
  </article>

</div>